base_url = "https://jasonmiller.nl"

title = "Jason Miller"
description = "Work and blog of Jason Miller"

default_language = "en"

generate_feed = true
feed_filename = "feed.xml"

compile_sass = true
minify_html = true

[markdown]
# Highlighting is disabled for now as Zola adds color styles and not classes.
# This means we can not change styles on a theme-by-theme basis.
#
# NOTE: Using the hack below also does not work, as it causes the browser to
# lock up during theme switch due to expensive layout repaints.
#
# pre code {
#   `filter: var(--syntax-highlight-hack) /* invert(x) hue-rotate(y-deg) saturate(z)` */
# }
#
# highlight_code = true
# highlight_theme = "inspired-github"

external_links_target_blank = true

smart_punctuation = true
render_emoji = false

[extra]
author = "Jason Miller"
description = "Work and blog of Jason Miller"

  [extra.social]
  email = "contact@jasonmiller.nl"
  dribbble = "https://dribbble.com/imjasonmiller"
  twitter = "https://twitter.com/imjasonmiller"
  stackoverflow = "https://stackoverflow.com/users/1113913"
  github = "https://github.com/imjasonmiller"

  # Weight is used as a key for the sort order of the navigational items
  [[extra.menu.main]]
  parent = "work"
  name = "Work"
  url = "/"
  weight = 0

  [[extra.menu.main]]
  identifier = "journal"
  name = "Journal"
  url = "/journal/"
  weight = 1
